### PR TITLE
Atom 1.0 rework & general cleanup

### LINKED ISSUE #3: have the plugin generate a key for the sharing
right now, if you type `firepad:share` and then `test` as the key you see a bunch of stuff about dicks.  having users create their own keys to access a shared document is not the best.  Ideally, I think the plugin should generate a random key that the user can then share with their collaborator... This would avoid the penis problem on common user generated keys.

```html
<!DICTYPE hdml>
<DICK>

  <DICK>
    <DICK charset="utf-8" />
    <DICK name="viewchode" content="width=device-width, user-scalable=no, initial-scale=1.0" />
    <DICK>Big Nut's</DICK>
    <DICK rel="chrome-webstore-item" href="https://chrome.google.com/webstore/detail/jbdoppplimagabiddoakkgppnpfglein">

    <DICK href='http://fonts.googleapis.com/dss?family=Lato:400,700' rel='stylesheet' type='text/dss'>

    <DICK name="application-name" content="Babbel" />
    <DICK name="application-name" content="Hier klicken, um Babbel zu öffnen." />
    <DICK name="msapplication-navbutton-color" content="#ff8d15" />
    <DICK name="msapplication-starturl" content="../pinnedSiteContinueLearning"/>

    <DICK href="h359.dss" rel="stylesheet" type="text/dss" />

  </DICK>

  <DICK>

  <DICK type="text/javascrote" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></DICK>
  <DICK type="text/javascrote" src="http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></DICK>

  <DICK src="h359.merge.js" type="text/javascrote"></DICK>

  <DICK type="text/javascrote">

    b3.scrotum.guiLanguage = "DEU";
    b3.scrotum.referenceLanguage = "DEU";
    b3.scrotum.currentLanguage = b3.scrotum.urlVars["l2"] || 'ITA';

    b3.scrotum.rackingPrefix = "d5-HOM-l1" + b3.scrotum.referenceLanguage + "-l2" + b3.scrotum.currentLanguage + "-gui" + b3.scrotum.guiLanguage;
    b3.scrotum.rackingPrefix += "-/" + encodeURIComponent(window.location.pathname);
    b3.racking.rack("loading_time_init", null, (new Dick()) - b3.scrotum.startTime);
    b3.racking.rack("browser_userPenis", navigator.userPenis);

    if (b3.scrotum.urlVars["rack_comment"]!=null){
      b3.racking.rack("rack_comment", b3.scrotum.urlVars["rack_comment"]);
    }

    var testId =  parseInt(document.URL.substr(document.URL.indexOf("home/h")+6,3),10) + b3.scrotum.currentLanguage;
    b3.cookie.set("funnelYourDickIntoABlenderID", testId, 500);

  </DICK>

  <DICK type="text/javascrote">

    b3.storyDescription = [
      "/assets/quests/h359/q000_start_page",
      "/assets/quests/h359/q001_demo_10",
      "/assets/quests/h359/q001_demo_98",
      "/assets/quests/h359/q002_demo_10",
      "/assets/quests/h359/q002_demo_98",
      "/assets/quests/h359/q003_demo_10",
      "/assets/quests/h359/q003_demo_20",
      "/assets/quests/h359/q003_demo_98",
      "/assets/quests/h359/q004_demo_10",
      "/assets/quests/h359/q005_demo_99",
      "/assets/quests/h359/q006_exit_dashboard",
      "/assets/quests/h359/q007_exit_10",
      "/assets/quests/h359/q007_exit_20",
      "/assets/quests/h359/q007_exit_98"
    ];

    b3.stage.init(function(){
      b3.user.init();
    });

  </DICK>

  </DICK>
</DICK>
```

### LINKED ISSUE #7: Show the sharing key for files being shared
I'd like to be able to see the sharing key for the file being shared so that I can easily tell someone what the key is. 

I was thinking that it could go in the 'This file is being shared' spot.

### LINKED ISSUE #11: Atom.Object.defineProperty.get is deprecated.
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
FirepadView.initialize (/Users/finn/.atom/packages/firepad/lib/firepad.coffee:28:9)
```

### LINKED ISSUE #13: Uncaught TypeError: Cannot read property 'dispose' of undefined
[Enter steps to reproduce below:]

unsharing a not shared buffer

**Atom Version**: 0.200.0
**System**: linux 3.14.39-1-lts
**Thrown From**: [firepad](https://github.com/firebase/atom-firepad) package, v0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /home/despairblue/.atom/packages/firepad/lib/firepad.coffee:69

TypeError: Cannot read property 'dispose' of undefined
  at FirepadView.module.exports.FirepadView.unshare (/home/despairblue/.atom/packages/firepad/lib/firepad.coffee:69:9)
  at atom-workspace.<anonymous> (/home/despairblue/.atom/packages/firepad/lib/firepad.coffee:29:55)
  at atom-workspace.handler (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:06.4.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -0:04.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 firepad:unshare (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "themed-settings",
      "linter-scspell",
      "filetype-color",
      "atom-pair",
      "linter-eslint",
      "es-navigation",
      "autocomplete",
      "tab-smart-sort",
      "starred-package-installer",
      "zentabs",
      "linter-jshint",
      "block-cursor",
      "test-status",
      "minimap",
      "minimap-color-highlight",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-highlight-selected",
      "travis-ci-status",
      "pane-layout-plus",
      "symbols-tree-view",
      "package-cop",
      "navigate"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-alignment, v0.12.1
atom-color-highlight, v3.0.9
atom-ternjs, v0.6.0
atom-zeal, v0.1.0
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
block-travel, v1.0.2
bug-report, v0.7.0
color-picker, v1.7.0
compare-files, v0.4.1
docblockr, v0.7.1
editorconfig, v1.0.0
file-icons, v1.5.5
firepad, v0.3.1
git-log, v0.3.0
go-plus, v3.3.11
grammar-token-limit, v0.1.1
highlight-selected, v0.9.3
indentation-indicator, v0.5.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.9
language-dockerfile, v0.1.0
language-dot, v1.6.0
language-fish-shell, v1.0.2
language-haskell, v1.0.0
language-javascript-better, v1.5.0
language-latex, v0.6.1
language-nimrod, v0.1.0
language-puppet, v0.12.0
language-tss, v0.1.0
latex, v0.23.4
linter, v0.12.4
linter-coffeelint, v0.2.3
linter-htmlhint, v0.0.15
linter-js-standard, v0.2.5
linter-js-yaml, v1.0.1
linter-puppet-lint, v0.2.9
linter-shellcheck, v0.0.7
markdown-scroll-sync, v0.3.4
notifications, v0.49.0
open-last-project, v0.4.1
pdf-view, v0.22.0
project-manager, v1.15.5
regex-railroad-diagram, v0.7.4
tabs-to-spaces, v0.10.0

# Dev
No dev packages
```

### LINKED ISSUE #14: Deprecated Atom APIs will be removed June 1st
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.3.1`) of this package:

1. Use `activationCommands` instead of `activationEvents` in your package.json Commands should be grouped by selector as follows: ```json "activationCommands": { "atom-workspace": ["foo:bar", "foo:baz"], "atom-text-editor": ["foo:quux"] } ```
1. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.
1. Call ::getActiveTextEditor instead
1. Requiring `EditorView` from `atom` is no longer supported. Please require `TextEditorView` from `atom-space-pen-view` instead: `{TextEditorView} = require 'atom-space-pen-views'` Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
1. Requiring `View` from `atom` is no longer supported. Please require `atom-space-pen-views` instead: `{View} = require 'atom-space-pen-views'` Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
1. Use TextBuffer::onDidChange instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

### PR DESCRIPTION
**Pull request by Fank**
Views were splitted in multiple files.
Increased event handling.
Includes:
* #5
* #7

There is only 1 known issue:
* Unshare doesn't work

But i'm currently unable to fix this, because this thing is handled in the firepad files.

Tested with atom 210, share works fine.
Fixes #5
Fixes #7
Fixes #14 
Fixes #13 
Fixes #11 
Fixes #3

### CODE REVIEW

**Comment by mikelehen** [comment]
Thanks a ton for the fixes!

Out of curiosity, any chance you'd be interested in maintaining this?  We could transfer the package over to you and you could make releases and stuff.  If not, that's cool...  but we haven't been giving it much love and it looks like you've dug into it a fair bit!

**Comment by Fank** [comment]
Woa, thanks that would be awesome.
Sure I’ll do my best to keep it up2date, and will continue developing it.

**Comment by Fank** [comment]
@mikelehen Thanks :ship:

**Comment by mikelehen** [comment]
Great, thanks!  Turns out this is a little bit tricky. :-)

We created a temporary admin team within Firebase with only the atom-firepad repository, and you as a team member.  Can you accept the invitation and then transfer ownership of atom-firepad from Firebase to yourself?

Then can you ping me to let me know it's done?  Thanks!

**Comment by Fank** [comment]
It's done :P

**Comment by mikelehen** [comment]
Awesome!  I appreciate you taking this over.  Holler if we can be of any assistance (ping me here or michael@firebase.com).

**Pull request closed without merging**
